repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml #checks yaml files for parseable syntax.
    -   id: end-of-file-fixer #ensures that a file is either empty, or ends with one newline.
    -   id: trailing-whitespace # trims trailing whitespace.
    -   id: check-json #checks json files for parseable syntax.
    -   id: requirements-txt-fixer #sorts entries in requirements.txt.
    -   id: check-added-large-files #prevents giant files from being committed.
    -   id: check-ast #simply checks whether the files parse as valid python.
    -   id: check-docstring-first #checks a common error of defining a docstring after code.
    -   id: check-merge-conflict #checks for files that contain merge conflict strings.
    -   id: detect-aws-credentials #detects *your* aws credentials from the aws cli credentials file.
    -   id: detect-private-key #detects the presence of private keys.
    -   id: name-tests-test #this verifies that test files are named correctly.
    -   id: sort-simple-yaml #sorts simple yaml files which consist only of top-level keys, preserving comments and blocks.
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
        args: [--line-length=120]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
    -   id: autopep8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bandit", "flake8-bugbear"]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
    -   id: detect-secrets

# test